name: Fun
main: to.joe.j2mc.fun.J2MC_Fun
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Fun module.
commands:
  item:
    description: Spawn items
    usage: /item iname/id:damage amount
    aliases: ['i','give']
    permission: j2mc.fun.commands
    permission-message: You may not
  ci:
    aliases: ['clearinventory']
    description: clear inventory
    usage: /ci
    permission: j2mc.fun.commands
    permission-message: You may not
permissions:
  j2mc.fun.commands:
    description: Gives access to fun commands.
  j2mc.fun.trusted:
    description: Trusted access
  j2mc.fun.admin:
    description: Admin access
    children:
      j2mc.fun.trusted: true
      j2mc.fun.commands: true
