name: J2MC_Fun
main: to.joe.j2mc.fun.J2MC_Fun
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Fun module.
commands:
  item:
    description: Spawn items
    usage: /item iname/id:damage amount
    aliases: ['i','give']
    permission: j2mc.fun
    permission-message: You may not
  ci:
    description: clear inventory
    usage: /ci
    permission: j2mc.fun
    permission-message: You may not
permissions:
  j2mc.fun:
    description: Gives access to fun commands.